# Generated by Django 4.0.4 on 2024-02-23 11:29

from django.db import migrations, models
import social_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_content',
            field=models.ImageField(blank=True, null=True, upload_to=social_media.models.profile_image_file_path),
        ),
    ]
